language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: GLpcjhuNTlCIl2mhZ0ZsFbvdRvWg56j1gsQXhnAiFwZZF2ACM6S2fiO9OLHH1b1C/vji2sF+nsQXS3Rau9SXQwlSbaqXTpaBnZU3C0zrg4YzH/JnKR1uM488LD2tGQky2imlofZL2A9iFb2eH60A0S5Azwb9aXCkzlOoUfneQWPIi94GFXK//prvuCJTg47ez2t/FjGljxIff0UzRcQJPsB/BjoR48bFn2CLAaAPv/y7ZuHnLdvjD4yIKPOKpvs6jHTEJ3pOclwSJ3iSgWN6NUtI5ks+UwQRNsj7WqMu7b2+74kgdkfVfdyp6v7XsAT4TnEbwgAp2EpzRlEdeWPfuooNdY/ycQTRteUFE5Xb2cLvS5EKJaEa8Cn8+vm52iupWOJJCgmnwkptaQdMhESL13u/vxFujiqtgUW+H98ibyLrUMfsVfx5L0Ef606sl34nOmeuiOoXexDGio7KPUDdcTxscyGLpXAthLVxMCMY0SEwflGdab7OhKObKf9nJVQbkabiZTJigafk0DRsNhNHhL6qmxnLn8Xj6tmyMom55LHQ1cMojH+2XVkMHlfC4FsWTwYX2OlZn9ppKz24cfKfkRyV6UTCBBJvQkILqqjq15K7fh6u2DQEskqxphiNcb91XLytB8cTfnEOOUE5yh9KElUII0PkNfkpgjC2ToR2H+0=
  app: react-trello-testing
  on:
    repo: Btan579/react-trello-testing
